name: Build Docker Image

on: [push]

jobs:
  build-step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

      - name: docker build & push
        run: |
          docker build -t docker.pkg.github.com/${{ github.repository_owner }}/solitudes .
          docker push docker.pkg.github.com/${{ github.repository_owner }}/solitudes
